var wms_layers = [];

var lyr_PKSOpaskartta_0 = new ol.layer.Tile({
                            source: new ol.source.TileWMS(({
                              url: "https://kartat.espoo.fi/TeklaOgcWeb/WMS.ashx",
                              attributions: ' ',
                              params: {
                                "LAYERS": "PKS_Opaskartta",
                                "TILED": "true",
                                "VERSION": "1.1.1"},
                            })),
                            title: 'PKS-Opaskartta',
                            popuplayertitle: 'PKS-Opaskartta',
                            type: '',
                            opacity: 1.000000,
                            
                            
                          });
              wms_layers.push([lyr_PKSOpaskartta_0, 0]);
var format_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1 = new ol.format.GeoJSON();
var features_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1 = format_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1.readFeatures(json_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1.addFeatures(features_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1);
var lyr_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1, 
                style: style_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1,
                popuplayertitle: 'luonnonhoito_kuviot_hakkuut — Espoon kaupunki',
                interactive: true,
                title: '<img src="styles/legend/luonnonhoito_kuviot_hakkuutEspoonkaupunki_1.png" /> luonnonhoito_kuviot_hakkuut — Espoon kaupunki'
            });
var format_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2 = new ol.format.GeoJSON();
var features_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2 = format_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2.readFeatures(json_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2.addFeatures(features_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2);
var lyr_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2, 
                style: style_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2,
                popuplayertitle: 'luonnonhoito_kuviot_hakkuut_ja_metsänhoito — Espoon kaupunki',
                interactive: true,
                title: '<img src="styles/legend/luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2.png" /> luonnonhoito_kuviot_hakkuut_ja_metsänhoito — Espoon kaupunki'
            });
var format_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3 = new ol.format.GeoJSON();
var features_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3 = format_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3.readFeatures(json_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3.addFeatures(features_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3);
var lyr_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3, 
                style: style_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3,
                popuplayertitle: 'luonnonhoito_kuviot_metsänhoito — Espoon kaupunki',
                interactive: true,
                title: '<img src="styles/legend/luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3.png" /> luonnonhoito_kuviot_metsänhoito — Espoon kaupunki'
            });
var format_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4 = new ol.format.GeoJSON();
var features_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4 = format_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4.readFeatures(json_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4.addFeatures(features_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4);
var lyr_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4, 
                style: style_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4,
                popuplayertitle: 'luonnonhoito_kuviot_ei_toimenpiteitä — Espoon kaupunki',
                interactive: true,
                title: '<img src="styles/legend/luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4.png" /> luonnonhoito_kuviot_ei_toimenpiteitä — Espoon kaupunki'
            });
var format_Pohjois_espoon_lohkojako_5 = new ol.format.GeoJSON();
var features_Pohjois_espoon_lohkojako_5 = format_Pohjois_espoon_lohkojako_5.readFeatures(json_Pohjois_espoon_lohkojako_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Pohjois_espoon_lohkojako_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Pohjois_espoon_lohkojako_5.addFeatures(features_Pohjois_espoon_lohkojako_5);
var lyr_Pohjois_espoon_lohkojako_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Pohjois_espoon_lohkojako_5, 
                style: style_Pohjois_espoon_lohkojako_5,
                popuplayertitle: 'Pohjois_espoon_lohkojako',
                interactive: false,
                title: '<img src="styles/legend/Pohjois_espoon_lohkojako_5.png" /> Pohjois_espoon_lohkojako'
            });

lyr_PKSOpaskartta_0.setVisible(true);lyr_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1.setVisible(true);lyr_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2.setVisible(true);lyr_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3.setVisible(true);lyr_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4.setVisible(true);lyr_Pohjois_espoon_lohkojako_5.setVisible(true);
var layersList = [lyr_PKSOpaskartta_0,lyr_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1,lyr_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2,lyr_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3,lyr_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4,lyr_Pohjois_espoon_lohkojako_5];
lyr_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1.set('fieldAliases', {'fid': 'fid', 'id': 'id', 'Kuvionumero': 'Kuvionumero', 'extension': 'extension', 'estate_code': 'estate_code', 'area': 'area', 'main_group': 'main_group', 'sub_group': 'sub_group', 'fertility_class': 'fertility_class', 'soil_type': 'soil_type', 'drainage_state': 'drainage_state', 'development_class': 'development_class', 'quality': 'quality', 'main_tree_species': 'main_tree_species', 'accessibility': 'accessibility', 'Kuviokuvaus': 'Kuviokuvaus', 'age': 'age', 'basal_area': 'basal_area', 'stem_count': 'stem_count', 'mean_diameter': 'mean_diameter', 'mean_height': 'mean_height', 'volume': 'volume', 'saw_log_volume': 'saw_log_volume', 'pulp_wood_volume': 'pulp_wood_volume', 'volume_growth': 'volume_growth', 'value': 'value', 'value_growth_percent': 'value_growth_percent', 'carbon_storage': 'carbon_storage', 'tree_carbon_storage': 'tree_carbon_storage', 'tree_carbon_flux': 'tree_carbon_flux', 'soil_carbon_storage': 'soil_carbon_storage', 'nature_value': 'nature_value', 'productive_value': 'productive_value', 'Suunniteltu hakkuu': 'Suunniteltu hakkuu', 'Suunniteltu metsänhoito': 'Suunniteltu metsänhoito', 'last_completed_harvest_operations': 'last_completed_harvest_operations', 'last_completed_silviculture_operations': 'last_completed_silviculture_operations', 'special_features': 'special_features', });
lyr_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2.set('fieldAliases', {'fid': 'fid', 'id': 'id', 'Kuvionumero': 'Kuvionumero', 'extension': 'extension', 'estate_code': 'estate_code', 'area': 'area', 'main_group': 'main_group', 'sub_group': 'sub_group', 'fertility_class': 'fertility_class', 'soil_type': 'soil_type', 'drainage_state': 'drainage_state', 'development_class': 'development_class', 'quality': 'quality', 'main_tree_species': 'main_tree_species', 'accessibility': 'accessibility', 'Kuviokuvaus': 'Kuviokuvaus', 'age': 'age', 'basal_area': 'basal_area', 'stem_count': 'stem_count', 'mean_diameter': 'mean_diameter', 'mean_height': 'mean_height', 'volume': 'volume', 'saw_log_volume': 'saw_log_volume', 'pulp_wood_volume': 'pulp_wood_volume', 'volume_growth': 'volume_growth', 'value': 'value', 'value_growth_percent': 'value_growth_percent', 'carbon_storage': 'carbon_storage', 'tree_carbon_storage': 'tree_carbon_storage', 'tree_carbon_flux': 'tree_carbon_flux', 'soil_carbon_storage': 'soil_carbon_storage', 'nature_value': 'nature_value', 'productive_value': 'productive_value', 'Suunniteltu hakkuu': 'Suunniteltu hakkuu', 'Suunniteltu metsänhoito': 'Suunniteltu metsänhoito', 'last_completed_harvest_operations': 'last_completed_harvest_operations', 'last_completed_silviculture_operations': 'last_completed_silviculture_operations', 'special_features': 'special_features', });
lyr_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3.set('fieldAliases', {'fid': 'fid', 'id': 'id', 'Kuvionumero': 'Kuvionumero', 'extension': 'extension', 'estate_code': 'estate_code', 'area': 'area', 'main_group': 'main_group', 'sub_group': 'sub_group', 'fertility_class': 'fertility_class', 'soil_type': 'soil_type', 'drainage_state': 'drainage_state', 'development_class': 'development_class', 'quality': 'quality', 'main_tree_species': 'main_tree_species', 'accessibility': 'accessibility', 'Kuviokuvaus': 'Kuviokuvaus', 'age': 'age', 'basal_area': 'basal_area', 'stem_count': 'stem_count', 'mean_diameter': 'mean_diameter', 'mean_height': 'mean_height', 'volume': 'volume', 'saw_log_volume': 'saw_log_volume', 'pulp_wood_volume': 'pulp_wood_volume', 'volume_growth': 'volume_growth', 'value': 'value', 'value_growth_percent': 'value_growth_percent', 'carbon_storage': 'carbon_storage', 'tree_carbon_storage': 'tree_carbon_storage', 'tree_carbon_flux': 'tree_carbon_flux', 'soil_carbon_storage': 'soil_carbon_storage', 'nature_value': 'nature_value', 'productive_value': 'productive_value', 'Suunniteltu hakkuu': 'Suunniteltu hakkuu', 'Suunniteltu metsänhoito': 'Suunniteltu metsänhoito', 'last_completed_harvest_operations': 'last_completed_harvest_operations', 'last_completed_silviculture_operations': 'last_completed_silviculture_operations', 'special_features': 'special_features', });
lyr_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4.set('fieldAliases', {'fid': 'fid', 'id': 'id', 'Kuvionumero': 'Kuvionumero', 'extension': 'extension', 'estate_code': 'estate_code', 'area': 'area', 'main_group': 'main_group', 'sub_group': 'sub_group', 'fertility_class': 'fertility_class', 'soil_type': 'soil_type', 'drainage_state': 'drainage_state', 'development_class': 'development_class', 'quality': 'quality', 'main_tree_species': 'main_tree_species', 'accessibility': 'accessibility', 'Kuviokuvaus': 'Kuviokuvaus', 'age': 'age', 'basal_area': 'basal_area', 'stem_count': 'stem_count', 'mean_diameter': 'mean_diameter', 'mean_height': 'mean_height', 'volume': 'volume', 'saw_log_volume': 'saw_log_volume', 'pulp_wood_volume': 'pulp_wood_volume', 'volume_growth': 'volume_growth', 'value': 'value', 'value_growth_percent': 'value_growth_percent', 'carbon_storage': 'carbon_storage', 'tree_carbon_storage': 'tree_carbon_storage', 'tree_carbon_flux': 'tree_carbon_flux', 'soil_carbon_storage': 'soil_carbon_storage', 'nature_value': 'nature_value', 'productive_value': 'productive_value', 'Suunniteltu hakkuu': 'Suunniteltu hakkuu', 'Suunniteltu metsänhoito': 'Suunniteltu metsänhoito', 'last_completed_harvest_operations': 'last_completed_harvest_operations', 'last_completed_silviculture_operations': 'last_completed_silviculture_operations', 'special_features': 'special_features', });
lyr_Pohjois_espoon_lohkojako_5.set('fieldAliases', {'id': 'id', 'Lohko': 'Lohko', 'pinta-ala': 'pinta-ala', });
lyr_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1.set('fieldImages', {'fid': 'TextEdit', 'id': 'TextEdit', 'Kuvionumero': 'TextEdit', 'extension': 'TextEdit', 'estate_code': 'TextEdit', 'area': 'TextEdit', 'main_group': 'TextEdit', 'sub_group': 'TextEdit', 'fertility_class': 'TextEdit', 'soil_type': 'TextEdit', 'drainage_state': 'TextEdit', 'development_class': 'TextEdit', 'quality': 'TextEdit', 'main_tree_species': 'TextEdit', 'accessibility': 'TextEdit', 'Kuviokuvaus': 'TextEdit', 'age': 'TextEdit', 'basal_area': 'TextEdit', 'stem_count': 'TextEdit', 'mean_diameter': 'TextEdit', 'mean_height': 'TextEdit', 'volume': 'TextEdit', 'saw_log_volume': 'TextEdit', 'pulp_wood_volume': 'TextEdit', 'volume_growth': 'TextEdit', 'value': 'TextEdit', 'value_growth_percent': 'TextEdit', 'carbon_storage': 'TextEdit', 'tree_carbon_storage': 'TextEdit', 'tree_carbon_flux': 'TextEdit', 'soil_carbon_storage': 'TextEdit', 'nature_value': 'TextEdit', 'productive_value': 'TextEdit', 'Suunniteltu hakkuu': 'TextEdit', 'Suunniteltu metsänhoito': 'TextEdit', 'last_completed_harvest_operations': 'TextEdit', 'last_completed_silviculture_operations': 'TextEdit', 'special_features': 'TextEdit', });
lyr_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2.set('fieldImages', {'fid': 'TextEdit', 'id': 'TextEdit', 'Kuvionumero': 'TextEdit', 'extension': 'TextEdit', 'estate_code': 'TextEdit', 'area': 'TextEdit', 'main_group': 'TextEdit', 'sub_group': 'TextEdit', 'fertility_class': 'TextEdit', 'soil_type': 'TextEdit', 'drainage_state': 'TextEdit', 'development_class': 'TextEdit', 'quality': 'TextEdit', 'main_tree_species': 'TextEdit', 'accessibility': 'TextEdit', 'Kuviokuvaus': 'TextEdit', 'age': 'TextEdit', 'basal_area': 'TextEdit', 'stem_count': 'TextEdit', 'mean_diameter': 'TextEdit', 'mean_height': 'TextEdit', 'volume': 'TextEdit', 'saw_log_volume': 'TextEdit', 'pulp_wood_volume': 'TextEdit', 'volume_growth': 'TextEdit', 'value': 'TextEdit', 'value_growth_percent': 'TextEdit', 'carbon_storage': 'TextEdit', 'tree_carbon_storage': 'TextEdit', 'tree_carbon_flux': 'TextEdit', 'soil_carbon_storage': 'TextEdit', 'nature_value': 'TextEdit', 'productive_value': 'TextEdit', 'Suunniteltu hakkuu': 'TextEdit', 'Suunniteltu metsänhoito': 'TextEdit', 'last_completed_harvest_operations': 'TextEdit', 'last_completed_silviculture_operations': 'TextEdit', 'special_features': 'TextEdit', });
lyr_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3.set('fieldImages', {'fid': 'TextEdit', 'id': 'TextEdit', 'Kuvionumero': 'TextEdit', 'extension': 'TextEdit', 'estate_code': 'TextEdit', 'area': 'TextEdit', 'main_group': 'TextEdit', 'sub_group': 'TextEdit', 'fertility_class': 'TextEdit', 'soil_type': 'TextEdit', 'drainage_state': 'TextEdit', 'development_class': 'TextEdit', 'quality': 'TextEdit', 'main_tree_species': 'TextEdit', 'accessibility': 'TextEdit', 'Kuviokuvaus': 'TextEdit', 'age': 'TextEdit', 'basal_area': 'TextEdit', 'stem_count': 'TextEdit', 'mean_diameter': 'TextEdit', 'mean_height': 'TextEdit', 'volume': 'TextEdit', 'saw_log_volume': 'TextEdit', 'pulp_wood_volume': 'TextEdit', 'volume_growth': 'TextEdit', 'value': 'TextEdit', 'value_growth_percent': 'TextEdit', 'carbon_storage': 'TextEdit', 'tree_carbon_storage': 'TextEdit', 'tree_carbon_flux': 'TextEdit', 'soil_carbon_storage': 'TextEdit', 'nature_value': 'TextEdit', 'productive_value': 'TextEdit', 'Suunniteltu hakkuu': 'TextEdit', 'Suunniteltu metsänhoito': 'TextEdit', 'last_completed_harvest_operations': 'TextEdit', 'last_completed_silviculture_operations': 'TextEdit', 'special_features': 'TextEdit', });
lyr_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4.set('fieldImages', {'fid': 'TextEdit', 'id': 'TextEdit', 'Kuvionumero': 'TextEdit', 'extension': 'TextEdit', 'estate_code': 'TextEdit', 'area': 'TextEdit', 'main_group': 'TextEdit', 'sub_group': 'TextEdit', 'fertility_class': 'TextEdit', 'soil_type': 'TextEdit', 'drainage_state': 'TextEdit', 'development_class': 'TextEdit', 'quality': 'TextEdit', 'main_tree_species': 'TextEdit', 'accessibility': 'TextEdit', 'Kuviokuvaus': 'TextEdit', 'age': 'TextEdit', 'basal_area': 'TextEdit', 'stem_count': 'TextEdit', 'mean_diameter': 'TextEdit', 'mean_height': 'TextEdit', 'volume': 'TextEdit', 'saw_log_volume': 'TextEdit', 'pulp_wood_volume': 'TextEdit', 'volume_growth': 'TextEdit', 'value': 'TextEdit', 'value_growth_percent': 'TextEdit', 'carbon_storage': 'TextEdit', 'tree_carbon_storage': 'TextEdit', 'tree_carbon_flux': 'TextEdit', 'soil_carbon_storage': 'TextEdit', 'nature_value': 'TextEdit', 'productive_value': 'TextEdit', 'Suunniteltu hakkuu': 'TextEdit', 'Suunniteltu metsänhoito': 'TextEdit', 'last_completed_harvest_operations': 'TextEdit', 'last_completed_silviculture_operations': 'TextEdit', 'special_features': 'TextEdit', });
lyr_Pohjois_espoon_lohkojako_5.set('fieldImages', {'id': 'TextEdit', 'Lohko': 'TextEdit', 'pinta-ala': 'TextEdit', });
lyr_luonnonhoito_kuviot_hakkuutEspoonkaupunki_1.set('fieldLabels', {'fid': 'hidden field', 'id': 'hidden field', 'Kuvionumero': 'inline label - visible with data', 'extension': 'hidden field', 'estate_code': 'hidden field', 'area': 'hidden field', 'main_group': 'hidden field', 'sub_group': 'hidden field', 'fertility_class': 'hidden field', 'soil_type': 'hidden field', 'drainage_state': 'hidden field', 'development_class': 'hidden field', 'quality': 'hidden field', 'main_tree_species': 'hidden field', 'accessibility': 'hidden field', 'Kuviokuvaus': 'inline label - visible with data', 'age': 'hidden field', 'basal_area': 'hidden field', 'stem_count': 'hidden field', 'mean_diameter': 'hidden field', 'mean_height': 'hidden field', 'volume': 'hidden field', 'saw_log_volume': 'hidden field', 'pulp_wood_volume': 'hidden field', 'volume_growth': 'hidden field', 'value': 'hidden field', 'value_growth_percent': 'hidden field', 'carbon_storage': 'hidden field', 'tree_carbon_storage': 'hidden field', 'tree_carbon_flux': 'hidden field', 'soil_carbon_storage': 'hidden field', 'nature_value': 'hidden field', 'productive_value': 'hidden field', 'Suunniteltu hakkuu': 'inline label - visible with data', 'Suunniteltu metsänhoito': 'inline label - visible with data', 'last_completed_harvest_operations': 'hidden field', 'last_completed_silviculture_operations': 'hidden field', 'special_features': 'hidden field', });
lyr_luonnonhoito_kuviot_hakkuut_ja_metsnhoitoEspoonkaupunki_2.set('fieldLabels', {'fid': 'hidden field', 'id': 'hidden field', 'Kuvionumero': 'inline label - visible with data', 'extension': 'hidden field', 'estate_code': 'hidden field', 'area': 'hidden field', 'main_group': 'hidden field', 'sub_group': 'hidden field', 'fertility_class': 'hidden field', 'soil_type': 'hidden field', 'drainage_state': 'hidden field', 'development_class': 'hidden field', 'quality': 'hidden field', 'main_tree_species': 'hidden field', 'accessibility': 'hidden field', 'Kuviokuvaus': 'inline label - visible with data', 'age': 'hidden field', 'basal_area': 'hidden field', 'stem_count': 'hidden field', 'mean_diameter': 'hidden field', 'mean_height': 'hidden field', 'volume': 'hidden field', 'saw_log_volume': 'hidden field', 'pulp_wood_volume': 'hidden field', 'volume_growth': 'hidden field', 'value': 'hidden field', 'value_growth_percent': 'hidden field', 'carbon_storage': 'hidden field', 'tree_carbon_storage': 'hidden field', 'tree_carbon_flux': 'hidden field', 'soil_carbon_storage': 'hidden field', 'nature_value': 'hidden field', 'productive_value': 'hidden field', 'Suunniteltu hakkuu': 'inline label - visible with data', 'Suunniteltu metsänhoito': 'inline label - visible with data', 'last_completed_harvest_operations': 'hidden field', 'last_completed_silviculture_operations': 'hidden field', 'special_features': 'hidden field', });
lyr_luonnonhoito_kuviot_metsnhoitoEspoonkaupunki_3.set('fieldLabels', {'fid': 'hidden field', 'id': 'hidden field', 'Kuvionumero': 'inline label - visible with data', 'extension': 'hidden field', 'estate_code': 'hidden field', 'area': 'hidden field', 'main_group': 'hidden field', 'sub_group': 'hidden field', 'fertility_class': 'hidden field', 'soil_type': 'hidden field', 'drainage_state': 'hidden field', 'development_class': 'hidden field', 'quality': 'hidden field', 'main_tree_species': 'hidden field', 'accessibility': 'hidden field', 'Kuviokuvaus': 'inline label - visible with data', 'age': 'hidden field', 'basal_area': 'hidden field', 'stem_count': 'hidden field', 'mean_diameter': 'hidden field', 'mean_height': 'hidden field', 'volume': 'hidden field', 'saw_log_volume': 'hidden field', 'pulp_wood_volume': 'hidden field', 'volume_growth': 'hidden field', 'value': 'hidden field', 'value_growth_percent': 'hidden field', 'carbon_storage': 'hidden field', 'tree_carbon_storage': 'hidden field', 'tree_carbon_flux': 'hidden field', 'soil_carbon_storage': 'hidden field', 'nature_value': 'hidden field', 'productive_value': 'hidden field', 'Suunniteltu hakkuu': 'inline label - visible with data', 'Suunniteltu metsänhoito': 'inline label - visible with data', 'last_completed_harvest_operations': 'hidden field', 'last_completed_silviculture_operations': 'hidden field', 'special_features': 'hidden field', });
lyr_luonnonhoito_kuviot_ei_toimenpiteitEspoonkaupunki_4.set('fieldLabels', {'fid': 'hidden field', 'id': 'hidden field', 'Kuvionumero': 'inline label - visible with data', 'extension': 'hidden field', 'estate_code': 'hidden field', 'area': 'hidden field', 'main_group': 'hidden field', 'sub_group': 'hidden field', 'fertility_class': 'hidden field', 'soil_type': 'hidden field', 'drainage_state': 'hidden field', 'development_class': 'hidden field', 'quality': 'hidden field', 'main_tree_species': 'hidden field', 'accessibility': 'hidden field', 'Kuviokuvaus': 'inline label - visible with data', 'age': 'hidden field', 'basal_area': 'hidden field', 'stem_count': 'hidden field', 'mean_diameter': 'hidden field', 'mean_height': 'hidden field', 'volume': 'hidden field', 'saw_log_volume': 'hidden field', 'pulp_wood_volume': 'hidden field', 'volume_growth': 'hidden field', 'value': 'hidden field', 'value_growth_percent': 'hidden field', 'carbon_storage': 'hidden field', 'tree_carbon_storage': 'hidden field', 'tree_carbon_flux': 'hidden field', 'soil_carbon_storage': 'hidden field', 'nature_value': 'hidden field', 'productive_value': 'hidden field', 'Suunniteltu hakkuu': 'inline label - visible with data', 'Suunniteltu metsänhoito': 'inline label - visible with data', 'last_completed_harvest_operations': 'hidden field', 'last_completed_silviculture_operations': 'hidden field', 'special_features': 'hidden field', });
lyr_Pohjois_espoon_lohkojako_5.set('fieldLabels', {'id': 'hidden field', 'Lohko': 'hidden field', 'pinta-ala': 'hidden field', });
lyr_Pohjois_espoon_lohkojako_5.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});